apiVersion: v1
kind: Service
metadata:
  name: casper-node
  labels:
    app: casper-node
spec:
  # ports:
  #   - port: 80
  #     name: web
  clusterIP: None
  selector:
    app: casper-node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: casper-node
spec:
  serviceName: "casper-node"
  replicas: 100
  selector:
    matchLabels:
      app: casper-node
  template:
    metadata:
      labels:
        app: casper-node
    spec:
      containers:
        - name: node
          image: clmarc/casper-node:784eb0e0
          resources:
          limits:
            cpu: "500m"
            mem: 1Gi
          requests:
            cpu: "250m"
            mem: 500Mi
  #       ports:
  #       - containerPort: 80
  #         name: web
  #       volumeMounts:
  #       - name: www
  #         mountPath: /usr/share/nginx/html
  # volumeClaimTemplates:
  # - metadata:
  #     name: www
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 1Gi
