[package]
name = "muxink"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bytes = "1.1.0"
futures = "0.3.21"
serde = { version = "1.0.137", optional = true }
thiserror = "1.0.31"
tokio = { version = "1.18.1", features = [ "full" ] }
tokio-util = "0.7.2"

[dev-dependencies]
tokio-stream = "0.1.8"

[features]
default = [ "serde" ]
