[package]
name = "casper-node"
version = "0.1.0"
authors = ["Marc Brinkmann <marc@casperlabs.io>",
           "Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2018"
description = "The CasperLabs blockchain node server"
publish = false  # Prevent accidental `cargo publish` for now.
license-file = "LICENSE"

[dependencies]
anyhow = "1.0.28"
async-trait = "0.1.31"
either = "1.5.3"
enum-iterator = "0.6.0"
futures = "0.3.5"
serde = { version = "1.0.110", features = ["derive"] }
smallvec = "1.4.0"
structopt = "0.3.14"
tokio = { version = "0.2.20", features = ["macros", "rt-threaded", "sync"] }
toml = "0.5.6"
tracing = "0.1.14"
tracing-subscriber = "0.2.5"
