[package]
name = "muxink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
bytes = "1.1.0"
futures = "0.3.21"
thiserror = "1.0.31"
tokio = { version = "1.18.1", features = ["full"] }
