[workspace]

members = [
    "ci/casper_updater",
    "client",
    "execution_engine",
    "execution_engine_testing/cargo_casper",
    "execution_engine_testing/test_support",
    "execution_engine_testing/tests",
    "node",
    "smart_contracts/contract",
    "smart_contracts/contracts/[!.]*/*",
    "types",
]

default-members = [
    "ci/casper_updater",
    "client",
    "execution_engine",
    "execution_engine_testing/cargo_casper",
    "execution_engine_testing/test_support",
    "execution_engine_testing/tests",
    "node",
    "smart_contracts/contract",
    "types",
]

exclude = ["casper-node-macros"]

# Include debug symbols in the release build of `casper-engine-tests` so that `simple-transfer` will yield useful
# perf data.
[profile.release.package.casper-engine-tests]
debug = true

[profile.release]
# TODO: nightly compiler has issues with linking libraries with LTO enabled.
# Change this back to true once stable is supported by default.
lto = false

[profile.bench]
lto = true

[patch.crates-io]
# A temporary patch for unreleased wasmi 0.8.x that depends on parity-wasm 0.42.2
# https://github.com/paritytech/wasmi/commit/f5fd480260490ff0de455017229caf7baee68195
wasmi = { git = "https://github.com/paritytech/wasmi", branch = "master" }