[package]
authors = ["Marc Brinkmann <marc@casperlabs.io>"]
edition = "2018"
name = "connection_manager"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.25"
