[package]
name = "revert"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>"]
edition = "2018"

[[bin]]
name = "revert"
bench = false
doctest = false
test = false

[features]
std = ["casperlabs-contract/std", "casperlabs-types/std"]

[dependencies]
casperlabs-contract = { path = "../../../contract" }
casperlabs-types = { path = "../../../../types" }
