[package]
name = "transfer-to-account-u512-stored"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "transfer_to_account_u512_stored"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["casperlabs-contract/std", "casperlabs-types/std"]

[dependencies]
casperlabs-contract = { path = "../../../contract" }
transfer-to-account-u512 = { path = "../transfer-to-account-u512" }
casperlabs-types = { path = "../../../../types" }
