[package]
name = "casper-node-macros"
version = "0.1.0"
authors = ["Marc Brinkmann <marc@casperlabs.io>"]
edition = "2018"

[dependencies]
indexmap = "1.6.0"
Inflector = "0.11.4"
proc-macro2 = "1.0.21"
syn = { version = "1.0.40", features = ["full"] }

[lib]
proc-macro = true
