[package]
name = "casper-execution-engine"
version = "0.7.0"
authors = ["Henry Till <henrytill@gmail.com>", "Ed Hastings <ed@casperlabs.io>"]
edition = "2018"
description = "CasperLabs execution engine crates."
readme = "README.md"
documentation = "https://docs.rs/casper-engine-shared"
homepage = "https://casperlabs.io"
repository = "https://github.com/CasperLabs/casper-node/tree/master/execution_engine"
license-file = "../LICENSE"

[dependencies]
base16 = "0.2.1"
blake2 = "0.8.1"
chrono = "0.4.10"
hostname = "0.3.0"
lazy_static = "1.4.0"
libc = "0.2.66"
log = { version = "0.4.8", features = ["std", "serde", "kv_unstable"] }
num = { version = "0.2.0", default-features = false }
parity-wasm = "0.41.0"
proptest = { version = "0.10.0", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_bytes = "0.11.5"
casper-types = { version = "0.6.0", path = "../types", package = "casper-types", features = ["std", "gens"] }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
wabt = "0.10.0"
thiserror = "1.0.18"
rmp-serde = "0.14.3"
hex_fmt = "0.3.0"
rand = "0.7.3"
num-traits = "0.2.10"
csv = "1.1.3"
hex = "0.4.2"
uint = "0.8.3"
tracing = "0.1.18"
rand_chacha = "0.2.2"
wasmi = "0.6.2"
num-derive = "0.3.0"
itertools = "0.8.2"
pwasm-utils = "0.12.0"
lmdb = "0.8"
linked-hash-map = "0.5.2"
anyhow = "1.0.28"

[dev-dependencies]
tempfile = "3.1.0"
assert_matches = "1.3.0"
proptest = "0.10.0"

[features]
default = ["gens"]
gens = ["proptest"]
test-support = []
no-unstable-features = ["casper-types/no-unstable-features"]

[package.metadata.docs.rs]
features = ["no-unstable-features"]