[package]
name = "counter-define"
version = "0.1.0"
authors = ["Ed Hastings <ed@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "counter_define"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["casper-contract/std", "casper-types/std"]

[dependencies]
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
