[package]
name = "counter-define"
version = "0.1.0"
authors = ["Ed Hastings <ed@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "counter_define"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["casperlabs-contract/std", "casperlabs-types/std"]

[dependencies]
casperlabs-contract = { path = "../../../contract" }
casperlabs-types = { path = "../../../../types" }
