[package]
name = "set-key-thresholds"
version = "0.1.0"
authors = ["Joe Sacher <joes@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "set_key_thresholds"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["casperlabs-contract/std", "casperlabs-types/std"]

[dependencies]
casperlabs-contract = { path = "../../../contract" }
casperlabs-types = { path = "../../../../types" }
