[package]
name = "auction"
version = "0.1.0"
authors = ["Michał Papierski <michal@papierski.net>"]
edition = "2018"

[lib]
bench = false
doctest = false
test = false

[features]
std = ["contract/std", "types/std"]

[dependencies]
casperlabs-contract = { path = "../../../contract" }
casperlabs-types = { path = "../../../../types" }
