[package]
name = "pos-install"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "pos_install"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["casperlabs-contract/std", "casperlabs-types/std"]

[dependencies]
base16 = { version = "0.2.1", default-features = false }
casperlabs-contract = { path = "../../../contract" }
pos = { path = "../pos" }
casperlabs-types = { path = "../../../../types" }
