[package]
name = "standard-payment-install"
version = "0.1.0"
authors = ["Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "standard_payment_install"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["casper-contract/std", "casper-types/std"]
no-unstable-features = ["casper-contract/no-unstable-features", "casper-types/no-unstable-features"]

[dependencies]
casper-contract = { path = "../../../contract" }
standard-payment = { version = "0.1.0", path = "../standard-payment" }
casper-types = { version = "0.6.0", path = "../../../../types" }
