[package]
name = "standard-payment-install"
version = "0.1.0"
authors = ["Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "standard_payment_install"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["casperlabs-contract/std", "casperlabs-types/std"]
no-unstable-features = ["casperlabs-contract/no-unstable-features", "casperlabs-types/no-unstable-features"]

[dependencies]
casperlabs-contract = { path = "../../../contract" }
standard-payment = { version = "0.1.0", path = "../standard-payment" }
casperlabs-types = { version = "0.6.0", path = "../../../../types" }
