[package]
name = "standard-payment"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>"]
edition = "2018"

[lib]
bench = false
doctest = false
test = false

[[bin]]
name = "standard_payment"
path = "src/bin/main.rs"

bench = false
doctest = false
test = false

[features]
std = ["casper-contract/std", "casper-types/std"]

[dependencies]
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
